### ISSUE TITLE
0.5.0 has problem No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader;

### ISSUE THREAD

**Issue by gengjiawen** [facebook/SoLoader#10]
Reproduce code: https://github.com/facebook/react-native/pull/19724#issuecomment-397522851.
0.3.0 works fine.

**Comment by passy** [comment]
I'm not seeing how to repro it there? We're using `0.5.0` in litho with the same call and aren't seeing this.

**Comment by gengjiawen** [comment]
* Checkout this pr https://github.com/facebook/react-native/pull/19724/files
* delete those line in build.gradle
```
   project.configurations.all {
       resolutionStrategy.eachDependency { details ->
           if (details.requested.group == 'com.facebook.soloader') {
               details.useVersion "0.3.0"
           }
       }
   }
```
* install RNTester app by `./gradlew :RNTester:android:app:installDebug`
* Launch the app, it will crash.

**Comment by gengjiawen** [comment]
Release won't build due to this too if you try `./gradlew :RNTester:android:app:installRelease`

**Comment by gengjiawen** [comment]
It works on windows, maybe something wrong with macOS.

**Comment by gengjiawen** [comment]
After restart macOS, the problem is gone ...

**Comment by gengjiawen** [comment]
During the build, I do try the `./gradlew clean` multi times, but the problem still exists. So if anyone run into something similar, maybe consider restart your macOS.

**Comment by gengjiawen** [comment]
This issue occurred in 0.5.1, see full log: https://circleci.com/gh/gengjiawen/react-native/676?utm_campaign=build-failed&utm_medium=email&utm_source=notification.

**Comment by gengjiawen** [comment]
@passy

**Comment by passy** [comment]
@gengjiawen This means that different SoLoader versions are mixed in the dependencies. Can you check with `./gradlew :ReactNative:dependencies` if that's the case?
