### ISSUE TITLE
Help me, I've done several settings and still the app crashes in the soloader

### ISSUE THREAD

**Issue by MarcosSarges** [facebook/SoLoader#102]
- ERROR Crashlytics
<img width="1280" alt="Screen Shot 2022-05-21 at 22 44 04" src="https://user-images.githubusercontent.com/40393115/169674806-ab0fd495-5e9b-4914-bdc2-d29838c57345.png">

------

- android/build.gradle

<img width="749" alt="Screen Shot 2022-05-21 at 09 49 04" src="https://user-images.githubusercontent.com/40393115/169674812-f38431e2-1c86-4c00-ae59-ada1cb16eee9.png">

<img width="832" alt="Screen Shot 2022-05-21 at 09 48 56" src="https://user-images.githubusercontent.com/40393115/169674852-e7b3b884-a8b4-409d-820c-c5dfd6719124.png">

------

- android/app/build.gradle

<img width="479" alt="Screen Shot 2022-05-21 at 09 47 59" src="https://user-images.githubusercontent.com/40393115/169674870-be18fcdd-180f-4952-bf62-a10da1052a99.png">
<img width="423" alt="Screen Shot 2022-05-21 at 09 48 11" src="https://user-images.githubusercontent.com/40393115/169674872-b24cb287-5d61-4cf2-b0e2-5c4d9b47bf6a.png">
<img width="758" alt="Screen Shot 2022-05-21 at 09 48 32" src="https://user-images.githubusercontent.com/40393115/169674873-168135e0-f8e8-49f7-957d-dd62120c8759.png">
<img width="809" alt="Screen Shot 2022-05-21 at 09 48 40" src="https://user-images.githubusercontent.com/40393115/169674874-c0ec4c25-4db0-45e5-ad6f-3ff52fa4315d.png">

------

- MainActivity.java
<img width="775" alt="Screen Shot 2022-05-21 at 22 49 01" src="https://user-images.githubusercontent.com/40393115/169674896-088132d0-925b-4faf-b1b4-dc324b6731d2.png">

------- 
- Gradle Version: 6.9-all

------

- RN INFO
```
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 125.16 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.18 - ~/<>/<>/<>/node_modules/.bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 21, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-31 | Google Play ARM 64 v8a
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Users/<>/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

# Any solution?

**Comment by DmitriyBetskikh** [comment]
The same Issue! 
My application was working fine, I didn't push  a new code for about a month, and two days ago I got the same crash when launching the application. I could not solve this problem in any way.
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/102299488/171618688-4de16e68-2881-484d-b5ca-cf16a001338e.png">

**Comment by arjun1194** [comment]
getting the same crash 
```
java.lang.UnsatisfiedLinkError: 
  at com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:1098)
  at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl (SoLoader.java:914)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:826)
  at com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:773)
  at com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:743)
  at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary (JSCExecutor.java:24)
  at com.facebook.react.jscexecutor.JSCExecutor.<clinit> (JSCExecutor.java:20)
  at com.facebook.react.jscexecutor.JSCExecutor.a (JSCExecutor.java)
  at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory (ReactInstanceManagerBuilder.java:352)
  at com.facebook.react.ReactInstanceManagerBuilder.build (ReactInstanceManagerBuilder.java:319)
  at com.facebook.react.ReactNativeHost.createReactInstanceManager (ReactNativeHost.java:95)
  at com.facebook.react.ReactNativeHost.getReactInstanceManager (ReactNativeHost.java:42)
  at com.myApplication.MainApplication.onCreate (MainApplication.kt:88)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1190)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6582)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:224)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1887)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
  
```

please help, the only other option is to remove facebook and react native from my project

**Comment by ivansnek** [comment]
> @MarcosSarges @DmitriyBetskikh @arjun1194 I was also having this same problem and affecting several users in my application. I updated to version 0.10.4 and made a hotfix for my entire user base. This type of crash is no longer being reported to me! Was solved! I made this decision via [this commit](https://github.com/facebook/SoLoader/commit/b28033f71c2f03eda75b728402db745d20d81875)! So I recommend upgrading to version 0.10.4 of the soloader!

@lfoliveir4  how did you updated? I've tried several approaches but no luck so far

1.- I tried the solution proposed [here](https://github.com/facebook/SoLoader/issues/59#issuecomment-669161376) using several versions, 0.10.4 included on both root and app build.gradle files

2.-  I tried also adding it as a dependency like  
```
implementation 'com.facebook.soloader:soloader:0.10.4'
```
I appreciate your help!

**Comment by Jamal-ReachFirst** [comment]
> > @MarcosSarges @DmitriyBetskikh @arjun1194 I was also having this same problem and affecting several users in my application. I updated to version 0.10.4 and made a hotfix for my entire user base. This type of crash is no longer being reported to me! Was solved! I made this decision via [this commit](https://github.com/facebook/SoLoader/commit/b28033f71c2f03eda75b728402db745d20d81875)! So I recommend upgrading to version 0.10.4 of the soloader!
> 
> @lfoliveir4 how did you updated? I've tried several approaches but no luck so far
> 
> 1.- I tried the solution proposed [here](https://github.com/facebook/SoLoader/issues/59#issuecomment-669161376) using several versions, 0.10.4 included on both root and app build.gradle files
> 
> 2.- I tried also adding it as a dependency like
> 
> ```
> implementation 'com.facebook.soloader:soloader:0.10.4'
> ```
> 
> I appreciate your help!

This massively increase the number of crashes. Didn't worked for me
