### ISSUE TITLE
Status code 503 from server

### ISSUE THREAD

**Issue by shubham-buccha** [facebook/SoLoader#103]
Getting this error while trying to run my react-native app.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.soloader:soloader:0.10.3+.
     Required by:
         project :app
      > Failed to list versions for com.facebook.soloader:soloader.
         > Unable to load Maven meta-data from https://repository.jboss.org/maven2/com/facebook/soloader/soloader/maven-metadata.xml.
            > Could not get resource 'https://repository.jboss.org/maven2/com/facebook/soloader/soloader/maven-metadata.xml'.
               > Could not GET 'https://repository.jboss.org/maven2/com/facebook/soloader/soloader/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

**Comment by passy** [comment]
That's a mirror that we don't control.
