### ISSUE TITLE
Wrongly loaded directApkLdPath

### ISSUE THREAD

**Issue by bimusiek** [facebook/SoLoader#104]
Hey, so I am debugging why when running AndroidTest the react-native cannot find libjscexecutor.
```
couldn't find DSO to load: libjscexecutor.so
```

As it turns out, it works when running the app, only fails when trying to run E2E tests with JUnit. 
I have checked where it tries to find the .so files and it looks like `getDirectApkLdPath` method returns wrong path.

```
  @Nullable
    private static String getDirectApkLdPath(String apkName) {
        String classLoaderLdLibraryPath = VERSION.SDK_INT >= 14 ? Api14Utils.getClassLoaderLdLoadLibrary() : null;
        if (classLoaderLdLibraryPath != null) {
            String[] paths = classLoaderLdLibraryPath.split(":");
            String[] var3 = paths;
            int var4 = paths.length;

            for(int var5 = 0; var5 < var4; ++var5) {
                String path = var3[var5];
                if (path.contains(apkName + ".apk!/")) {
                    return path;
                }
            }
        }

        return null;
    }
```

Content of `classLoaderLdLibraryPath` is as follows:
```
/data/app/~~ImiNm7Ho4oJpbguwZl6Vkg==/com.freeyourmusic.stamp.rc.test-okrbi8sdrNCbcK4yZzUjBQ==/lib/arm64:/data/app/~~8gISSyIdx--EqigOjP1Exg==/com.freeyourmusic.stamp.rc-4BoEP3mOszeNIgWC3ni6nQ==/lib/arm64:/data/app/~~ImiNm7Ho4oJpbguwZl6Vkg==/com.freeyourmusic.stamp.rc.test-okrbi8sdrNCbcK4yZzUjBQ==/base.apk!/lib/arm64-v8a:/data/app/~~8gISSyIdx--EqigOjP1Exg==/com.freeyourmusic.stamp.rc-4BoEP3mOszeNIgWC3ni6nQ==/base.apk!/lib/arm64-v8a
```

Which means the soLoader picks `com.freeyourmusic.stamp.rc.test` to look for libjscexecutor, where it should pick `com.freeyourmusic.stamp.rc` where it is located. 

Please correct me if I am wrong here, but I have spent last 2 days debugging why Android E2E tests cannot load libjscexecutor and this is the only reason I found.

**Comment by bimusiek** [comment]
@simpleton  I can confirm that the fix for this works (by building soloader from the main branch and using .aar in the Android project).

**Comment by simpleton** [comment]
Thank for the detailed issue and confirmation, much appreciated!
