### ISSUE TITLE
ArrayStoreException in ExtraFormZipSoSource.java

### ISSUE THREAD

**Issue by voiddog** [facebook/SoLoader#11]
My online app found this problem and it happened 30 times per day

Stack details:

Caused by:
--
* java.lang.ArrayStoreException:com.facebook.soloader.ExtractFromZipSoSource$ZipDso cannot be stored in an array of type com.facebook.soloader.ExtractFromZipSoSource$ZipDso[]
* java.util.AbstractCollection.toArray(AbstractCollection.java:196)
* com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker.ensureDsos
* com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker.getDsoManifest
* ...

**Comment by umeshchand1507** [comment]
I too seeing this issue in my app.

**Comment by simpleton** [comment]
This issue should be addressed in v0.10.3.
