### ISSUE TITLE
Next version release

### ISSUE THREAD

**Issue by vivascu** [facebook/SoLoader#121]
The SoLoader has not been published since almost a year now. Can we expect a new release anytime soon? Or should one just create a PR for it?

**Comment by adicatana** [comment]
Hi! We’re planning on shipping a new release in a few weeks, around mid December.

**Comment by vivascu** [comment]
> Hi! We’re planning on shipping a new release in a few weeks, around mid December.

Awesome, thanks for your answer. Looking forward to it.
