### ISSUE TITLE
Is it possible build this project with Gradle

### ISSUE THREAD

**Issue by conncui** [facebook/SoLoader#16]
buck require strict environment， it's not easy-to-use.
This project build for android ,Is it possible build this project with Gradle ？

**Comment by conncui** [comment]
i build this project in Ubuntu

**Comment by passy** [comment]
Why do you need to build this from source? We currently don't have gradle support in the project and are unlikely to add it in the future as we've already got a working release process with buck.

**Comment by conncui** [comment]
@passy Thanks for you reply.
There are some reason that i need to build with from source.
1. i need to firgure out SoLoader  principle，so it may be need to build with source ,even change code.

2. Buck tools is stranger for Android Developer , it seem "deps/BUCK" "scripts soloader_defs.bzl" have an effect on the final out file

**Comment by conncui** [comment]
i fork this project and build with gradle. it seem ok
https://github.com/conncui/SoLoader

**Comment by passy** [comment]
Awesome. Good to see that this was relatively straight-forward. I think adding it here wouldn't be of much value as we currently don't have any spare cycles to maintain that. But copying it over from your project should work for anyone who needs it.
