### ISSUE TITLE
Can't load libraries that are in dynamic feature modules

### ISSUE THREAD

**Issue by DSteve595** [facebook/SoLoader#19]
I'm trying to include a React Native activity in a [dynamic feature module](https://developer.android.com/studio/projects/dynamic-delivery#create_dynamic_feature). It works when it's included in the base APK, but it looks like [some hackery](https://developer.android.com/guide/app-bundle/playcore#aia_update_context) is needed when loading native libraries that are in an installed dynamic feature module: `SplitInstallHelper.loadLibrary()` should be used on 26+ rather than `System.loadLibrary()`. Currently I'm getting a crash saying the native library couldn't be found, and this seems like the most likely culprit.
 Since SoLoader is the one making the actual call, I'm not sure how I could do that from my end. I tried using `sSystemLoadLibraryWrapper`, but it looks like my `loadLibrary()` never gets called.

**Comment by DSteve595** [comment]
Thanks so much!

**Comment by erksch** [comment]
@DSteve595 How did you resolve the issue?

**Comment by DSteve595** [comment]
> @DSteve595 How did you resolve the issue?

It was resolved by #26.

**Comment by erksch** [comment]
So you are using the patched So loader from @nesterov-n?

**Comment by DSteve595** [comment]
It was merged. See https://github.com/facebook/SoLoader/commit/c7980fc4e77bbd45ab6febf4e6084f3c5bca03c3

**Comment by erksch** [comment]
Weird, it doesn't work for me. The SoLoader does not find the native libraries:

``` 
D/SoLoader: About to load: libjscexecutor.so
D/SoLoader: libjscexecutor.so not found on /data/data/<package>/lib-main
D/SoLoader: libjscexecutor.so not found on /data/data/<package>/lib-0
D/SoLoader: libjscexecutor.so not found on /data/data/<package>/lib-1
D/SoLoader: libjscexecutor.so not found on /data/app/<package>-LxW4qT73Kp0GBM4oUp20OQ==/lib/arm64
D/SoLoader: libjscexecutor.so not found on /vendor/lib
D/SoLoader: libjscexecutor.so not found on /system/lib
E/SoLoader: couldn't find DSO to load: libjscexecutor.so result: 0
``` 

The native libraries are actually located in 
```
/data/data/<package>/files/splitcompat/3/native-libraries/dynamicfeature.config.arm64_v86/
``` 
But the SoLoader does not seem to pick up this path. I wonder why it would work for you if your libs are in the same location.

**Comment by erksch** [comment]
I guess the difference is that you are using dynamic feature modules with split APKs while I am using them with App Bundles (.aar). As I see it https://github.com/facebook/SoLoader/pull/26 only added support for loading native libraries from the `lib-x` folders of split APKs. But with App Bundles they are in a completely different spot. Is that true for your case @DSteve595?

**Comment by erksch** [comment]
I found that the error is actually not that the files are in a different place, but that `applicationInfo.splitSourceDirs` or even `applicationInfo.splitNames` is null. Even when the dynamic feature is properly installed. This way the implementation of #26 can't pick up the libraries properly. But I wonder what causes that the `splitSourceDirs` property is not set correctly. Using `SplitInstallHelper.updateAppInfo()` after installation does not help.

**Comment by bembem1011** [comment]
I met same problem, when apply dynamic module using React Native activity :(

**Comment by erksch** [comment]
@bembem1011 do you have the same problem that `splitSourceDirs` is null? I wrote a patched SoLoader that also looks in `/data/data/<package>/files/splitcompat/x/native-libraries` for libraries maybe you could try that out.

**Comment by bembem1011** [comment]
I haven't found the rootcause yet, but if you can share it with me, I want to try out :( thanks you very much

**Comment by erksch** [comment]
You can use [my fork of SoLoader on the develop branch](https://github.com/erksch/SoLoader/tree/develop), build it and include the AAR in your project and see if it works.

Should be something like
```groovy
dependencies {
      ...
     implementation ('com.facebook.react:react-native:+') {
          exclude group: 'com.facebook.soloader', module: 'soloader'
     }
     implementation name: 'soloader', ext: 'aar'
}
repositories{
      flatDir{
              dirs 'libs'
       }
}
```

**Comment by bembem1011** [comment]
thanks @erksch today I will try your patch

**Comment by bembem1011** [comment]
@erksch :( sorry for my silly question
I see your patch in https://github.com/erksch/SoLoader/commit/32d6299b6187d7effa9315abe9b65d3d32622e4f
Now I have to install buck to build file aar. However I met a small below bug :( I try to search google but haven't found reason how to install buck fail like mine.

:( Do you have any solution about my issue below :( 

<img width="1236" alt="Screen Shot 2021-02-20 at 2 11 07 PM" src="https://user-images.githubusercontent.com/24663764/108587404-f1d45080-7385-11eb-9315-be1bd5e5ca31.png">

**Comment by bembem1011** [comment]
thanks @erksch you save my life. Your patch is work well, however I haven't understood deeply yet. When I read the debug log, I see splitResourceDirs is not null.  However, the soloader cannot load the library correctly without your patch. 
The default code (above your code patch) 
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP
                  && context.getApplicationInfo().splitSourceDirs != null) {
                Log.d(TAG, "adding backup sources from split apks");
                int splitIndex = 0;
                for (String splitApkDir : context.getApplicationInfo().splitSourceDirs) {
                  ApkSoSource splitApkSource =
                      new ApkSoSource(
                          context,
                          new File(splitApkDir),
                          SO_STORE_NAME_SPLIT + (splitIndex++),
                          apkSoSourceFlags);
                  Log.d(TAG, "adding backup source: " + splitApkSource.toString());
                  backupSources.add(splitApkSource);
                }
              }`

`
    2021-02-21 04:25:03.016 16635-16635/com.company.myapp D/SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.company.myapp-F73hOhmdUiA3L91mlttZLw==/lib/arm64 flags = 0]
    2021-02-21 04:25:03.017 16635-16635/com.company.myapp D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.company.myapp/lib-main flags = 1]
    2021-02-21 04:25:03.017 16635-16635/com.company.myapp D/SoLoader: adding backup sources from split apks
    2021-02-21 04:25:03.017 16635-16635/com.company.myapp D/SoLoader: adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.company.myapp/lib-0 flags = 1]
    2021-02-21 04:25:03.017 16635-16635/com.company.myapp D/SoLoader: adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.company.myapp/lib-1 flags = 1]
    2021-02-21 04:25:03.017 16635-16635/com.company.myapp D/SoLoader: adding backup source: com.facebook.soloader.ApkSoSource[root = /data/data/com.company.myapp/lib-2 flags = 1]
`

**Comment by varunon9** [comment]
@erksch @bembem1011 might be a silly request but can you share soloader.aar file? I am facing the same issue and want to try this solution.

**Comment by fcduarte** [comment]
> You can use [my fork of SoLoader on the develop branch](https://github.com/erksch/SoLoader/tree/develop), build it and include the AAR in your project and see if it works.
> 
> Should be something like
> 
> ```groovy
> dependencies {
>       ...
>      implementation ('com.facebook.react:react-native:+') {
>           exclude group: 'com.facebook.soloader', module: 'soloader'
>      }
>      implementation name: 'soloader', ext: 'aar'
> }
> 
> repositories {
>       flatDir {
>            dirs 'libs'
>       }
> }
> ```

@erksch this should be incorporated on the main SoLoader, I don't feel the current version can handle "splitcompat" folders given the amount of issues the community have, just search for "android app bundles java.lang.UnsatisfiedLinkError: couldn't find DSO to load" and most people will be stuck in the same problem.

**Comment by belemaire** [comment]
@erksch Thanks much for this patch, we were facing the same issue and it did its magic 👍 
Any reason why you didn't opened a PR to have this patch in a next SoLoader release ? 
Given the amount of users now reporting their problem being fixed by your patch, it would make sense.

**Comment by erksch** [comment]
@fcduarte @belemaire I'm glad my patch worked for you. I can open a PR, but I think my addition is kind of hacky and maybe needs some polishing before going into the main branch.

**Comment by erksch** [comment]
@varunon9 
I uploaded the AAR [here](https://drive.google.com/file/d/18EDser0XbovJuXXWI37zzhNHXWDb1LGP/view?usp=sharing).
But building it from source is not that difficult.
