### ISSUE TITLE
soloader caused Application not responding

### ISSUE THREAD

**Issue by apue** [facebook/SoLoader#35]
Description
I called below code:

ImagePipelineConfig config = ImagePipelineConfig.newBuilder(context)
        .setDownsampleEnabled(true)
        .build();

Fresco.initialize(context, config);
and got below ANR:
java.util.regex.Matcher in openImpl
java.util.regex.Matcher in usePattern at line 238
java.util.regex.Matcher in at line 89
java.util.regex.Pattern in matcher at line 297
com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker in ensureDsos at line 79
com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker in getDsoManifest at line 137
com.facebook.soloader.UnpackingSoSource in refreshLocked at line 324
com.facebook.soloader.UnpackingSoSource in prepare at line 420
com.facebook.soloader.SoLoader in initSoSources at line 266
com.facebook.soloader.SoLoader in init at line 170
com.facebook.soloader.SoLoader in init at line 153
com.facebook.drawee.backends.pipeline.Fresco in initialize at line 61
com.facebook.drawee.backends.pipeline.Fresco in initialize at line 44
com.mycompany.FrescoImageView in init at line 294

Another kind of ANR stacktrace is:
libcore.io.Posix in fsync
libcore.io.BlockGuardOs in fsync at line 143
java.io.FileDescriptor in sync at line 74
com.facebook.soloader.UnpackingSoSource in writeState at line 176
com.facebook.soloader.UnpackingSoSource in refreshLocked at line 321
com.facebook.soloader.UnpackingSoSource in prepare at line 420
com.facebook.soloader.SoLoader in initSoSources at line 266
com.facebook.soloader.SoLoader in init at line 170
com.facebook.soloader.SoLoader in init at line 153
com.facebook.drawee.backends.pipeline.Fresco in initialize at line 61
com.facebook.drawee.backends.pipeline.Fresco in initialize at line 44
com.mycompany.FrescoImageView in init at line 294

Reproduction
It is an online ANR, I can't reproduce it on my phone, however it happens more than 100 times per day.

Solution
N/A

Additional Information
Fresco version: 1.10.0
Platform version: from 4.4 to 9.0

btw, I moved the issue from fresco to soloader.

**Comment by yangkai3** [comment]
i meet the same problem, but i can reproduce it on some device (redmi 5a).
it is same with your stack, but i found that call "entries.nextElement()" many many many times, so the "ensureDsos" method cost a lot of time (1s).

**Comment by simpleton** [comment]
Version 0.10.3 has been released which includes this fix.

**Comment by Garfield0308** [comment]
> Version 0.10.3 has been released which includes this fix.

I didn't find the issue resolved in v0.10.3
