### ISSUE TITLE
App Bundle : couldn't find DSO to load: libfb.so

### ISSUE THREAD

**Issue by JeromeCHA** [facebook/SoLoader#46]
We tried to use App Bundle on our native Android app, but it crashes right after we launch the installed apks with the following error:
```
2019-08-27 16:48:27.394 E/com.facebook.soloader.NativeLibrary: Failed to load native lib: 
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfb.so
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:455)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:371)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:336)
        at com.facebook.soloader.NativeLibrary.loadLibraries(NativeLibrary.java:56)
        at com.facebook.soloader.NativeLibrary.ensureLoaded(NativeLibrary.java:77)
        at com.facebook.android.crypto.keychain.AndroidCryptoLibrary.ensureCryptoLoaded(AndroidCryptoLibrary.java:32)
        at com.facebook.crypto.Crypto.isAvailable(Crypto.java:57)
```
With apk, it works fine.

Even the "patched" here, on the merged PR, doesn't work for us https://github.com/facebook/SoLoader/pull/26

We've made some research and it looks like it is related to this issue, but we couldn't figure out how to fix it. https://github.com/facebook/react-native/issues/23764
Should we have to wait until this issue is fixed? or does anyone know how to fix it?

Edit: We are using
`implementation ("com.facebook.conceal:conceal:2.0.2@aar")`

Thank you in advance :)

**Comment by barnhill** [comment]
We have run into this as well.

**Comment by JeromeCHA** [comment]
Since It has been 1 week after I post this issue, does anyone know if they are working on it or not?

**Comment by victorlaerte** [comment]
We are also having this problem 😢

**Comment by oprisnik** [comment]
SoLoader 0.8.0 should fix this problem. We didn't release a Fresco version that bundles it yet, but you can force the version, see https://github.com/facebook/react-native/issues/25490#issuecomment-534570333

**Comment by victorlaerte** [comment]
@oprisnik is there any idea when a new version for `com.facebook.conceal` using 0.8.0 will be released?

**Comment by JeromeCHA** [comment]
I am also waiting for a newest version of `com.facebook.conceal` using 0.8.0 ^^

**Comment by oprisnik** [comment]
In the meantime, does [forcing the SoLoader version to 0.8.0](https://github.com/facebook/react-native/issues/25490#issuecomment-534570333) not work for conceal?

**Comment by courptwayne** [comment]
+1

**Comment by JeromeCHA** [comment]
> In the meantime, does [forcing the SoLoader version to 0.8.0](https://github.com/facebook/react-native/issues/25490#issuecomment-534570333) not work for Conceal?
@oprisnik I tried, but I still have the same error

**Comment by victorlaerte** [comment]
@JeromeCHA yeah, it doesn't work. :(

**Comment by barnhill** [comment]
Any update on this?

**Comment by wooyukit** [comment]
same here
![Screenshot 2019-12-04 at 4 18 27 PM](https://user-images.githubusercontent.com/11748275/70125504-dc580580-16b1-11ea-81e3-67dc4900a389.png)

Any solution for this?

**Comment by barnhill** [comment]
They don't seem to support this any longer

**Comment by wooyukit** [comment]
😱
I am using Litho framework for my project so I must init soloader at beginning. 😩

**Comment by illwiz** [comment]
please release new conceal version that use the latest soloader, back to using apk :(

**Comment by illwiz** [comment]
> > In the meantime, does [forcing the SoLoader version to 0.8.0](https://github.com/facebook/react-native/issues/25490#issuecomment-534570333) not work for Conceal?
> 
> @oprisnik I tried, but I still have the same error. 😥
> Does anyone have tried?

Tried it and https://github.com/facebook/react-native/issues/25415#issuecomment-541404167
still facing `java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfb.so`

**Comment by barnhill** [comment]
Tried this as well ... No luck :(

Brad Barnhill, MSN, RN
bradbarnhill@hotmail.com

**Comment by kakali** [comment]
There is one optimisation that might still work (it does in my case), instead of using plain old fat apk. We may still use aab, but disable splitting by architecture. To do this, we have to add a _bundle_ {} block within the _android_ {} block in the build.gradle file:

```
bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = false
        }
    }
```

Of course, it's still just a workaround.

**Comment by barnhill** [comment]
This is not a workaround as some of us the major benefit of bundling would come from splitting by arch.

**Comment by kakali** [comment]
> This is not a workaround as some of us the major benefit of bundling would come from splitting by arch.

Yep, I know. I'm lucky that in my app the main benefit comes from splitting by resources. Another thought was, maybe it would be possible to still split by arch and everything, but keep a dependency (conceal in this case) fat (?). But I didn't pursue this further.

**Comment by barnhill** [comment]
I'm working on getting rid of conceal now by replacing it with the AndroidX
security lib.

Brad Barnhill, MSN, RN
bradbarnhill@hotmail.com

**Comment by ahmetkocu** [comment]
Hi @barnhill,

Did you successfully migrate the library? How can we decrypt old data?

Is there a way to decrypt old data without Conceal lib?

**Comment by barnhill** [comment]
We left the conceal lib in and decrypted with it.  Then we encrypted with Tink.  After several months of converting in place we removed conceal.

**Comment by nb7123** [comment]
See the issues [REPO](https://github.com/nb7123/soloader-issues)

**Comment by simpleton** [comment]
Version 0.10.3 has been released which includes this fix.
