### ISSUE TITLE
readlink failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by sweggersen** [facebook/SoLoader#47]
I get the following error:
Caused by: android.system.ErrnoException: readlink failed: EACCES (Permission denied)
1 | libcore.io.Posix.readlink | Posix.java
2 | libcore.io.BlockGuardOs.readlink | BlockGuardOs.java, line 235
3 | android.system.Os.readlink | Os.java, line 372
4 | com.facebook.soloader.SysUtil$LollipopSysdeps.getSupportedAbis

I'm using a version that includes #45 Optimize extraction strategy. From the stacktrace it looks like this is the line it's crashing at: 
https://github.com/facebook/SoLoader/commit/b2555b82643e26d8830a876a64e43a040b4e3280#diff-fbed63fbbcc576af65201760b6baf3daR131

Is there another way to find out if we're using 64-bit?

I get thousands of these errors from users with various devices (HUAWEI ALE-L21, SAMSUNG, SM-J500M, HUAWEI CAM-L03, SAMSUNG SM-J700M, HUAWEI ALE-L23) and Android versions (99.9% of crashes comes from this range: Android 5.0 - Android 6.0.1)

**Comment by oprisnik** [comment]
We saw the same issue internally. That's why I merged f3883dfbb0a9acf80c37993c6aaeb78d9d143c14 shortly after the original PR was merged. It should fall back to the system behavior if something goes wrong.

The fix should be included in 0.8.0. Can you check if that fixes the issue?

**Comment by sweggersen** [comment]
Thanks! If you saw the same issues and fixed in on your side, I assume it's been fixed. I'll try 0.8.0 and reopen if I see the error again.
