### ISSUE TITLE
Use labels to mark issues in the repo

### ISSUE THREAD

**Issue by iadeelzafar** [facebook/SoLoader#52]
🙌 Hi!

I found SoLoader very interesting and wanted to contribute to it. But i found out that the issues in the repo are not marked with labels. So, it is quite to difficult to filter out the issues I could work on.

Would it be possible if you could mark the issues with relevant labels? Also, if there are any `good first issues` please let me know, I'd love to put my part in this open source loader.

**Comment by simpleton** [comment]
Thanks for your interest. I saw `Labels` has enabled.
