### ISSUE TITLE
D/ApkSoSource: not allowing consideration of ... deferring to libdir

### ISSUE THREAD

**Issue by JacobSolomonUCF** [facebook/SoLoader#57]
Hi,

We are developing a GIS Application and we are using React Native to support both iOS and Android. Our company's primary GIS Provider is Esri and they provide both an iOS SDK and Android SDK for consuming their services. We have created a port to allow us to integrate their SDK with our RN project. 

Our issue is that during the initial install of the Android application we are seeing the below error message which results in a white screen. The solution to this is to re-launch the application and the error goes away. I am unsure if the error is a problem with the Android SDK provided by Esri or ApkSoSource.

Any additional information that can be provided on why we are receiving this error would be greatly beneficial.

Thanks,
Jacob 

Ref: https://community.esri.com/thread/246073-android-sdk-weird-behavior

```
D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libc++_shared.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libfb.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libfolly_futures.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libfolly_json.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libglog.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libglog_init.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libimagepipeline.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libjsc.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libjscexecutor.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libjsijniprofiler.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libjsinspector.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libnative-filters.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libnative-imagetranscoder.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libreactnativeblob.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libreactnativejni.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libruntimecore.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libruntimecore_java.so: deferring to libdir
 not allowing consideration of lib/arm64-v8a/libyoga.so: deferring to libdir
```

**Comment by JacobSolomonUCF** [comment]
Issue's root cause was related to the version of the ArcGIS Android SDK

**Comment by JWesorick** [comment]
For any people arriving here from Googling their issue:

I ran into this issue when I enabled Proguard. It did something bad and disabling Proguard fixed my issue. If you want to keep Proguard enabled you can probably configure the pro guard rules to stop it from breaking your stuff.
