### ISSUE TITLE
Manifest merger failed: Duplicate package name

### ISSUE THREAD

**Issue by PaulWoitaschek** [facebook/SoLoader#58]
When adding soloader 0.8.0 my build fails with an error in the manifest merger:

```
[com.facebook.soloader:soloader:0.8.0] /home/ph1b/.gradle/caches/transforms-2/files-2.1/8f085a1fa1db60fbcb92924ed2143bb2/jetified-soloader-0.8.0/AndroidManifest.xml Error:
	Package name 'com.facebook.soloader' used in: com.facebook.soloader:soloader:0.8.0, com.facebook.soloader:annotation:0.8.0.
/home/ph1b/repos/SoLoaderBug/app/src/main/AndroidManifest.xml Error:
	Validation failed, exiting
```

> This is because I followed the advise from: https://developer.android.com/studio/releases/gradle-plugin:
> 
> The correct usage of unique package names are currently not enforced but will become more strict on later versions of the plugin. On Android Gradle plugin version 3.4.0, you can opt-in to check whether your project declares acceptable package names by adding the line below to your gradle.properties file.
> 
> android.uniquePackageNames = true

It would be great if you gave the annotations artifact a proper unique package name.

**Comment by mozarty** [comment]
+1

**Comment by junesolar** [comment]
How to fix this? I

**Comment by ZacSweers** [comment]
The annotations artifact is a native java library, yet for some reason soloader is distributing it as an aar. Will try to fix in a proposal PR
