### ISSUE TITLE
No static method loadLibrary

### ISSUE THREAD

**Issue by zhoufuqiang15** [facebook/SoLoader#62]
java.lang.NoSuchMethodError: No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader; or its super classes (declaration of 'com.facebook.soloader.SoLoader' appears in base.apk)
at com.facebook.yoga.YogaNode.<clinit>(YogaNode.java:24)

**Comment by passy** [comment]
This appears to be a version mismatch between the Yoga version and the SoLoader version you use.
