### ISSUE TITLE
Question: What is the difference between SoLoader and ReLinker?

### ISSUE THREAD

**Issue by maxim-pandra** [facebook/SoLoader#65]
ReLinker is "A robust native library loader for Android"

SoLoader is a native code loader for Android. It takes care of unpacking your native libraries and recursively loads dependencies on platforms that don't support that out of the box.

What should I choose for native library loading? What is the difference between the two?

**Comment by artyomdangizyan** [comment]
Relinked and SoLoader are both addressing the issue that pre lollipop versions are not loading so's dependencies before loading the so file. If you are targeting android 5.0 or higher you don't have that issue the bionic linker already does that. Besides that SoLoader has some extra functionality for looking for so files in the apk archive or other directories.

**Comment by philippb** [comment]
https://github.com/KeepSafe/ReLinker/wiki
