### ISSUE TITLE
New Release (0.10.0?)

### ISSUE THREAD

**Issue by alsutton** [facebook/SoLoader#70]
Hi Folks,

Just wondering if there are plans to create a new release? The last one was April last year and there have been a number of fixes since then which are on master.

Thanks.

**Comment by passy** [comment]
Hey @alsutton! 👋
Great call. I'll look into it.

**Comment by alsutton** [comment]
👋 Thank you kind Sir. Hope life is treating you well.

**Comment by passy** [comment]
@alsutton 0.10.0 should be on Maven Central. Waiting for the commit here to land, too.

**Comment by passy** [comment]
All done! Now to upgrade all the gazillions of projects depending on this.
