### ISSUE TITLE
Any guide for update from 0.2.0 to 0.3.0

### ISSUE THREAD

**Issue by ransj** [facebook/SoLoader#8]
I am investigate to update SoLoader to 0.3.0 used by react native. But i found class SoLoaderShim is missing. Any guide for update from 0.2.0 to 0.3.0?

**Comment by oprisnik** [comment]
I guess you're referring to Fresco's `SoLoaderShim`? You should use SoLoader directly, see https://github.com/facebook/fresco/commit/aef3790d3429833599d8b5529602e2c12f18c8aa
