### ISSUE TITLE
Native Crash on Android 6

### ISSUE THREAD

**Issue by haneewow** [facebook/SoLoader#82]
After update to version 0.9.0+ we started getting an error on devices from version 6. 

On version 0.8.0 this works but the following updates have important fixes for appBundle please help to solve the problem

* * * * * * * * * * * * * * * *
Build fingerprint: 'Xiaomi/markw/markw:6.0.1/MMB29M/V10.2.2.0.MBEMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 30167, tid: 30167, name: m.example.kl  >>> com.example.kl <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c0a454c8
    x0   000000557953cd10  x1   000000006fb22d08  x2   000000006fb22d28  x3   000000006fc1b104
    x4   0000000000080401  x5   0000000000020000  x6   000000001448fbf0  x7   0000000000000000
    x8   00000000705bfa68  x9   0000000000000000  x10  000000006fbd01c4  x11  0000000000880011
    x12  000000006fb22d28  x13  0000000070281290  x14  0000007feb2b65f8  x15  000000557953bea0
    x16  0000007feb2b65e8  x17  0000007feb2b7f58  x18  00000000000028a2  x19  000000000000d8c3
    x20  0000007feb2b6610  x21  0000007f7b5b2338  x22  0000000000000000  x23  00000000702dff5c
    x24  000000007034c574  x25  00000000541f1072  x26  0000000070281300  x27  000000006fc1b0d8
    x28  000000001448fbf0  x29  0000007feb2b6660  x30  0000007fa9e230e0
    sp   0000007feb2b6610  pc   0000007fa9e230fc  pstate 0000000000000000

backtrace:
    #00 pc 00000000002aa0fc  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb1EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+2320)
    #01 pc 00000000002afef4  /system/lib64/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE4ELb0ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+1168)
    #02 pc 00000000000ef434  /system/lib64/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+20068)
    #03 pc 000000000028718c  /system/lib64/libart.so (artInterpreterToInterpreterBridge+480)
    #04 pc 00000000002a9b74  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb1EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+904)
    #05 pc 00000000002ad060  /system/lib64/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE1ELb0ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+716)
    #06 pc 00000000000ef618  /system/lib64/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb1ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+20552)
    #07 pc 000000000028718c  /system/lib64/libart.so (artInterpreterToInterpreterBridge+480)
    #08 pc 00000000002a9280  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+480)
    #09 pc 00000000000dd688  /system/lib64/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+22200)
    #10 pc 0000000000286c90  /system/lib64/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+96)
    #11 pc 000000000053c140  /system/lib64/libart.so (artQuickToInterpreterBridge+632)
    #12 pc 0000000000128124  /system/lib64/libart.so (art_quick_to_interpreter_bridge+100)
    #13 pc 00000000733435a0  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x2564000)

**Comment by simpleton** [comment]
can you try it with v0.10.3?
