### ISSUE TITLE
Android app bundle crashes of soloader：Anyone can run my issues sample

### ISSUE THREAD

**Issue by nb7123** [facebook/SoLoader#83]
[see the sample repo](https://github.com/nb7123/soloader-issues)
When load yoga library, need load it's deps library libfb.so, crash.
I analyze the probably reason.
See the detail in my issues [REPO](https://github.com/nb7123/soloader-issues)

**Comment by nb7123** [comment]
JNI DETECTED ERROR IN APPLICATION: JNI GetFieldID called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.facebook.jni.Countable"

**Comment by simpleton** [comment]
Cool! Thanks for the issue and repro sample. I will look into it tomorrow.

**Comment by nb7123** [comment]
Solve this problem maybe like this:
when SoLoader load a library, first load it use System.loadLibrary, if load failed, use it's own load logic.
thanks

**Comment by nb7123** [comment]
> Cool! Thanks for the issue and repro sample. I will look into it tomorrow.

Has any problem email to me, thanks

**Comment by simpleton** [comment]
Hey @passy , is there any job that I can trigger to dumb a new version?
